### ISSUE TITLE
Remove .DS_Store and other temp files and add it to .gitignore

### ISSUE THREAD

**Issue by testzcrypto** [utopian-io/utopian-io-landingpage#43]
Example: https://github.com/utopian-io/utopian-io-landingpage/blob/master/.DS_Store

**Comment by mktcode** [comment]
Thanks! I will do that!

**Comment by mktcode** [comment]
https://github.com/utopian-io/utopian-io-landingpage/commit/0cde5a5bcb4fc2bf3f2c44d8280a2413c546db46
