### ISSUE TITLE
Wrongly Rendered Search Listing

### ISSUE THREAD

**Issue by Akintunde102** [utopian-io/utopian-io-landingpage#62]
Today, I was doing a search on my pc with the string "utopian.io" and I came across this. (Check  encircled portion of the picture below)

![uto.JPG](https://res.cloudinary.com/hpiynhbhq/image/upload/v1512961584/ytuasncclcid5mqqzpvc.jpg)

As you can see, instead of the right words being rendered as seen in the front end, it seems the back end code  is being  shownthe way it was crawled by the robot and subsequently rendered by the google search in the same way,as it is below:

`{{ moderator.account }}. {{ moderator.should_receive_rewards | currency }} SBD. {{ moderator.total_paid_rewards | currency }} SBD. {{ rewards.moderators.pending | currency }} SBD. {{ rewards.moderators.previous | currency }} SBD. {{ trans('messages.nav.blog') }}. utopian.io. ${TITLE} ${DATE}`

This doesn't make the site look professional in the face of new users who most likely would be programmers too.

So I suggest a thorough check on how this can be corrected.
## Below are the details of the bughunt:
**Operating System:** Windows 7 Ultimate 
**Browser:**Firefox Quantum 57.0.2 
**Search Engine**: Google
**Time:** 4:10 am (Nigerian TIme)
**PC:** HP PAVILION 2000

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@akintunde/bad-rendered-search-listing">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by mktcode** [comment]
Fixed in https://github.com/utopian-io/utopian-io-landingpage/commit/d18e7b229554984d2058a57cff938177e6fb76ce
Thanks!

**Comment by Akintunde102** [comment]
U are welcome

Good Job
