### ISSUE TITLE
FAQ link broken

### ISSUE THREAD

**Issue by alex-osman** [utopian-io/utopian-io-landingpage#66]
#### Description
The FAQ link on the homepage is broken under the `Who Pays For The Rewards` section does not work correctly.

#### Screenshot
![out.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513578686/xnswnrdm1vhrckx9no9r.gif)

#### Steps to reproduce:
First go to join.utopian.io.  Scroll down until you see the section titled `Who Pays For The Rewards`.  Click on the link that says `"Check the FAQs"`.

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@walnut1/faq-link-broken">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by mktcode** [comment]
Thank you! This will be fixed in the next update.
